export const productsBD = [
	{
		id: 1,
        productImg: "img_shop_1.jpg",
        category: "Mundo abierto",
		name: "The Legend of Zelda: Breath of the Wild 2",
		priceNormal: 35.000,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 2,
        productImg: "img_shop_2.jpg",
        category: "Mundo abierto",
		name: "The Last of Us Parte II",
		priceNormal: 143.000,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 3,
        productImg: "img_shop_3.jpg",
        category: "Mundo abierto",
		name: "Fallout 4",
		priceNormal: 86.000,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 4,
        productImg: "img_shop_4.jpg",
        category: "Mundo abierto",
		name: "The Witcher 3: Wild Hunt",
		priceNormal: 399.000,
        priceDiscount: 379.180,
		textOffert: "10% OFF",
        featured: true,
	},

	{
		id: 5,
        productImg: "img_shop_5.jpg",
        category: "Mundo abierto",
		name: "Grand Theft Auto V",
		priceNormal: 138.500,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},
	
	{
		id: 6,
        productImg: "img_shop_6.jpg",
        category: "Plataformas",
		name: "Psychonauts 2",
		priceNormal: 110.000,
        priceDiscount: 94.270,
		textOffert: "15% OFF",
        featured: false,
	},

	{
		id: 7,
        productImg: "img_shop_7.jpg",
        category: "Plataformas",
		name: "Hollow Knight",
		priceNormal: 381.934,
        priceDiscount: null,
		textOffert: null,
        featured: true,
	},

	{
		id: 8,
        productImg: "img_shop_8.jpg",
        category: "Plataformas",
		name: "9 Years of Shadows",
		priceNormal: 742.828,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 9,
        productImg: "img_shop_9.jpg",
        category: "Deportes",
		name: "EA Sports FIFA 23",
		priceNormal: 8.550,
        priceDiscount: 6.562,
		textOffert: "5% OFF",
        featured: true,
	},

	{
		id: 10,
        productImg: "img_shop_10.jpg",
        category: "Deportes",
		name: "Virtua Tennis 4",
		priceNormal: 15.790,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 11,
        productImg: "img_shop_11.jpg",
        category: "FPS",
		name: "DOOM Eternal",
		priceNormal: 7.200,
        priceDiscount: 4.069,
		textOffert: "20% OFF",
        featured: false,
	},


	{
		id: 12,
        productImg: "img_shop_12.jpg",
        category: "FPS",
		name: "Wolfenstein: The New Order",
		priceNormal: 18.325,
        priceDiscount: null,
		textOffert: null,
        featured: true,
	},

	{
		id: 13,
        productImg: "img_shop_13.jpg",
        category: "FPS",
		name: "Max Payne 3",
		priceNormal: 37.610,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 14,
        productImg: "img_shop_14.jpg",
        category: "FPS",
		name: "Half-Life 2",
		priceNormal: 18.500,
        priceDiscount: 11.738,
		textOffert: "15% OFF",
        featured: true,
	},

	{
		id: 15,
        productImg: "img_shop_15.jpg",
        category: "FPS",
		name: "Call of Duty: Warzone 2.0",
		priceNormal: 25.500,
        priceDiscount: null,
		textOffert: null,
        featured: false,
	},

	{
		id: 16,
        productImg: "img_shop_16.jpg",
        category: "FPS",
		name: "Left 4 Dead 2",
		priceNormal: 192.600,
        priceDiscount: null,
		textOffert: null,
        featured: true,
	},
];